export const ACTIONS = {
    INCBREAK: "INC_BREAK",
    DECBREAK: "DEC_BREAK",
    INCSESSION: "INC_SESSION",
    DECSESSION: "DEC_SESSION",
    PLAY: "PLAY",
    PAUSE: "PAUSE",
    RESET: "RESET"
}

